### ISSUE TITLE
6.4.0 certain playlist causes `innertube.getPlaylist` to report `This playlist does not exist`

### ISSUE THREAD

**Issue by PikachuEXE** [LuanRT/YouTube.js#516] opened 2023-10-02 01:15 UTC
### Steps to reproduce

- Save following script into a file e.g. `script.js`
- Install `youtube.js` (I did this in FreeTube project folder)
- `node script.js`

```js
const { Innertube } = require('youtubei.js')

async function createInnertube(options = { withPlayer: false, location: undefined, safetyMode: false, clientType: undefined, generateSessionLocally: true }) {
  return await Innertube.create({
    enable_safety_mode: false,
    generate_session_locally: !!options.generateSessionLocally
  })
}

(async () => {
  const innertube = await createInnertube()
  let playlist = await innertube.getPlaylist('PLT1F2nOxLHOcmi_qi1BbY6axf5xLFEcit')

  const videos = playlist.items

  while (playlist.has_continuation) {
    playlist = await playlist.getContinuation()

    videos.push(...playlist.items)
  }

  console.info('Done!', videos.length)
})()
```

### Failure Logs

```shell
// Playlist ID: PLT1F2nOxLHOcmi_qi1BbY6axf5xLFEcit

/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:11568
      throw new InnertubeError("This playlist does not exist");
            ^

InnertubeError: This playlist does not exist
    at new Playlist (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:11568:13)
    at Playlist2.<anonymous> (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:11593:14)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/pikachuexe/projects/electron/FreeTube/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  date: 2023-10-02T01:07:41.952Z,
  version: '6.4.0'
}
```

### Expected behavior

No error

### Current behavior

Error reported as seen in log

### Version

Default

### Anything else?

- https://www.youtube.com/playlist?list=PLT1F2nOxLHOcmi_qi1BbY6axf5xLFEcit
- https://github.com/FreeTubeApp/FreeTube/issues/4086

There is another error type reported for another playlist https://youtube.com/playlist?list=PLcyItF5YjT0dYq2E7Oti1pgBsRNq3A3jW
Not sure if should be reported here too
Error message is `There are too many continuations, you'll need to find the correct one yourself in this.page`

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by LuanRT** [comment] 2023-10-02 03:06
Fixed in https://github.com/LuanRT/YouTube.js/commit/8e372d5c67f148be288bb0485f2c70ec43fbecd0 & https://github.com/LuanRT/YouTube.js/commit/987f50604a0163f9a07091ce787995c6f6fddb75.

**Closed by LuanRT** 2023-10-02 03:06 UTC
Labels: bug, priority: high

**Comment by PikachuEXE** [comment] 2023-10-04 00:48
There is a new errors thrown (Same script)

#### playlist `PLT1F2nOxLHOcmi_qi1BbY6axf5xLFEcit`
The script should be getting just the 1st page here
https://www.youtube.com/playlist?list=PLT1F2nOxLHOcmi_qi1BbY6axf5xLFEcit

```
/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:11637
      throw new InnertubeError("Got empty continuation response. This is likely the end of the playlist.");
            ^

InnertubeError: Got empty continuation response. This is likely the end of the playlist.
    at new Playlist (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:11637:13)
    at Playlist2.<anonymous> (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:11662:14)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/pikachuexe/projects/electron/FreeTube/node_modules/tslib/tslib.js:166:62)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  date: 2023-10-04T00:43:09.708Z,
  version: '6.4.1'
}

```

#### playlist `PLcyItF5YjT0dYq2E7Oti1pgBsRNq3A3jW`
https://youtube.com/playlist?list=PLcyItF5YjT0dYq2E7Oti1pgBsRNq3A3jW

```
ParsingError: Type mismatch, got FeedFilterChipBar expected CommentsHeader | ItemSectionHeader | ItemSectionTabbedHeader.
    at ERROR_HANDLER (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:10399:20)
    at Object.parseItem (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:10680:13)
    at new ItemSection (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:6219:34)
    at parseItem (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:10698:22)
    at Object.parseArray (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:10718:22)
    at new SectionList (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:1127:36)
    at Object.parseItem (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:10698:22)
    at new Tab (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:8997:35)
    at parseItem (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:10698:22)
    at Object.parse (/Users/pikachuexe/projects/electron/FreeTube/node_modules/youtubei.js/bundle/node.cjs:10736:22) {
  info: {
    contents: [ [Object], [Object], [Object] ],
    trackingParams: 'CCcQ4M4DIhMIo56-65PbgQMVkldgCh3_lwCu',
    styleType: 'FEED_FILTER_CHIP_BAR_STYLE_TYPE_HASHTAG_LANDING_PAGE'
  },
  date: 2023-10-04T00:39:29.159Z,
  version: '6.4.1'
}
```

**Comment by absidue** [comment] 2023-10-04 05:51
@PikachuEXE Yes the first one is intentional, I told you so on the FreeTube repo and also how to deal with it.

You can ignore the second one though, it's printed with console.warn.

**Comment by PikachuEXE** [comment] 2023-10-04 07:04
For the 2nd one is a warning I get it

For the 1st one I am simply confused by `has_continuation()` returning `true` in which the code checks for `(this.#memo.get('ContinuationItem') || []).length > 0`
While `getContinuationData()` checks for `this.#continuation.length === 0`

Should `has_continuation()` use `this.#continuation.length` instead? (i.e. Can library users rely on `has_continuation` solely or have to catch error from `getContinuation`?)

**Comment by absidue** [comment] 2023-10-04 07:08
YouTube includes the continuation token in their first page response, the issue is not with YouTube.js's checks, it's with YouTube returning a useless continuation token. But we don't know it's useless/broken until we send that continuation token to YouTube and it returns a broken response.

**Comment by absidue** [comment] 2023-10-04 07:11
If you open the playlist on the YouTube website and scroll all the way down, you'll notice in the network tools that it requests the continuation as well.
