### ISSUE TITLE
This is a bug, please report it at

### ISSUE THREAD

**Issue by 0xhex** [LuanRT/YouTube.js#777] opened 2024-10-09 20:31 UTC
### Steps to reproduce

the video url : https://www.youtube.com/watch?v=dQw4w9WgXcQ

### Failure Logs

```shell
Extracted Video ID: dQw4w9WgXcQ
YouTubeAI initialized successfully.
[YOUTUBEJS][Parser]: InnertubeError: Something went wrong at ShortsLockupView!
This is a bug, please report it at https://github.com/LuanRT/YouTube.js/issues
    at ERROR_HANDLER (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14521:32)
    at parseItem (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14885:7)
    at Object.parseArray (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14901:22)
    at new ReelShelf (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:7069:33)
    at parseItem (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14881:22)
    at Object.parseArray (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14901:22)
    at new StructuredDescriptionContent (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:7101:33)
    at Object.parseItem (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14881:22)
    at new EngagementPanelSectionList (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:7124:35)
    at parseItem (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14881:22) {
  info: {
    stack: "TypeError: Cannot destructure property 'content' of 'data' as it is undefined.\n" +
      '    at Text.fromAttributed (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:5534:13)\n' +
      '    at new ShortsLockupView (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:12576:26)\n' +
      '    at parseItem (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at Object.parseArray (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14901:22)\n' +
      '    at new ReelShelf (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:7069:33)\n' +
      '    at parseItem (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at Object.parseArray (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14901:22)\n' +
      '    at new StructuredDescriptionContent (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:7101:33)\n' +
      '    at Object.parseItem (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:14881:22)\n' +
      '    at new EngagementPanelSectionList (/Users/efekanpulatli/Documents/CustomNodeJSProjects/youtubetext/node_modules/youtubei.js/bundle/node.cjs:7124:35)',
    classdata: '{\n' +
      '  "entityId": "shorts-shelf-item--8yWWBQJvx0",\n' +
      '  "accessibilityText": "Cruffin ❤️, 13 million views - play Short",\n' +
      '  "thumbnail": {\n' +
      '    "sources": [\n' +
      '      {\n' +
      '        "url": "https://i.ytimg.com/vi/-8yWWBQJvx0/oar2.jpg?sqp=-oaymwEdCJUDENAFSFWQAgHyq4qpAwwIARUAAIhCcAHAAQY=&rs=AOn4CLBVpH_djrVEIVJVnAuYTM2ObE_liw",\n' +
      '        "width": 405,\n' +
      '        "height": 720\n' +
      '      }\n' +
      '    ]\n' +
      '  },\n' +
      '  "onTap": {\n' +
      '    "innertubeCommand": {\n' +
      '      "clickTrackingParams": "CF4Qh_YEGAAiEwjgj6j8kIKJAxXhRU8EHcV7MyOaAQUIRRD4HQ==",\n' +
      '      "commandMetadata": {\n' +
      '        "webCommandMetadata": {\n' +
      '          "url": "/shorts/-8yWWBQJvx0",\n' +
      '          "webPageType": "WEB_PAGE_TYPE_SHORTS",\n' +
      '          "rootVe": 37414\n' +
      '        }\n' +
      '      },\n' +
      '      "reelWatchEndpoint": {\n' +
      '        "videoId": "-8yWWBQJvx0",\n' +
      '        "playerParams": "8AEByANFuAQfogYVAa6PwSY-JoGV2kdCS77Z13Z4iuiTkAcC",\n' +
      '        "thumbnail": {\n' +
      '          "thumbnails": [\n' +
      '            {\n' +
```

### Expected behavior

works

### Current behavior

error log

### Version

Default

### Checklist

- [X] I am running the latest version.
- [X] I checked the documentation and found no answer.
- [X] I have searched the existing issues and made sure this is not a duplicate.
- [X] I have provided sufficient information.

**Comment by absidue** [comment] 2024-10-09 21:12
Duplicate of #771 will be fixed in the next release, you can ignore it for the moment, as it probably doesn't affect anything you are doing on the watch page.

**Closed by absidue** 2024-10-09 21:12 UTC
Labels: bug
